---

- name: Clone repo
  git: repo={{ app.repo_url }} dest={{ app.dir }}

- name: npm install
  npm: path={{app.dir}}

- name: npm install pm2
  npm: name=pm2 global=yes

- name: start app
  shell: PORT=8004 npm run production
    chdir={{app.dir}}

- name: start app when system boots
  shell: pm2 startup ubuntu
    chdir={{app.dir}}

- name: setup nginx conf
  template: src=galant.nginx.j2 dest=/etc/nginx/sites-available/galant
- name: Enable nginx config
  file: src=/etc/nginx/sites-available/galant dest=/etc/nginx/sites-enabled/galant state=link
  notify:
    - restart nginx
