---

- name: Clone repo
  git: repo={{ app.repo_url }} dest={{ app.dir }}

- name: npm install
  npm: path={{app.dir}}

- name: npm install pm2
  npm: name=pm2 global=yes

- name: start app
  shell: pm2 restart app.js
    chdir={{app.dir}}
